server:
  port: ${PORT:8000}
  forward-headers-strategy: framework

spring:
  application:
    name: servlet-gateway-proxy
  cloud:
    gateway:
      mvc:
        routes:
          - id: events-upstream
            uri: ${EVENTS_SERVICE_URL:http://events-service:8082}
            predicates:
              - Path=/api/events/**
logging:
  level:
    org.springframework: DEBUG



proxy:
  migration-on: ${GRADUAL_MIGRATION:false}

  weight: ${MOVIES_MIGRATION_PERCENT:0}
  # Used only with PROXY_MODE=weighted

  upstream-a:
    uri: ${MONOLITH_URL:http://backend-v1:8080}

  upstream-b:
    uri: ${MOVIES_SERVICE_URL:http://backend-v2:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true
